# Use root/example as user/password credentials
version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.49
    restart: always
    ports:
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "14269:14269"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
